jwt:
  secret: e6d47f714cb6ebed1e8a79b7271a48b2b5701f463d9073526d0aa0a65df9bf2b # sha256 hashcode
  expiration-milliseconds: 1800000 #30 minutes

spring:
  application:
    name: spring_security_ex
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
# security - step 2
#  security:
#    user:
#      name: test
#      password: 1111
#      roles: USER